#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testShortOpts() {
  export PGOP_GLOBAL=(
    "f: filters:"
    "-  output"
    "q: query:"
    "b  version"
  )
  assertEquals "f:q:b" "$(__pgop_short_opts)"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
