#!/usr/bin/env bash
source $(dirname $0)/../lib/getopt.inc

function testGetoptShort() {
  ATO_GLOBAL=()
  assertEquals "when nothing is set" "" "$(__ato_getopt_short global)"

  ATO_GLOBAL=("1 one x x")
  assertEquals "no argument" "1" "$(__ato_getopt_short global)"

  ATO_GLOBAL=("1: one: x x")
  assertEquals "required argument" "1:" "$(__ato_getopt_short global)"

  ATO_GLOBAL=("1:: one:: x x")
  assertEquals "optional argument" "1::" "$(__ato_getopt_short global)"

  # multiple arguments
  ATO_GLOBAL=()
  ATO_GLOBAL+=("1   one x x")
  ATO_GLOBAL+=("2:  two: x x")
  ATO_GLOBAL+=("3:: three:: x x")
  assertEquals "complex argument" "12:3::" "$(__ato_getopt_short global)"
}

function testGetoptLong() {
  ATO_GLOBAL=()
  assertEquals "when nothing is set" "" "$(__ato_getopt_long global)"

  ATO_GLOBAL=("1 one x x")
  assertEquals "no argument" "one" "$(__ato_getopt_long global)"

  ATO_GLOBAL=("1: one: x x")
  assertEquals "required argument" "one:" "$(__ato_getopt_long global)"

  ATO_GLOBAL=("1:: one:: x x")
  assertEquals "optional argument" "one::" "$(__ato_getopt_long global)"

  # multiple arguments
  ATO_GLOBAL=()
  ATO_GLOBAL+=("1   one x x")
  ATO_GLOBAL+=("2:  two: x x")
  ATO_GLOBAL+=("3:: three:: x x")
  assertEquals "complex argument" "one,two:,three::" "$(__ato_getopt_long global)"
}

function testGetoptSetOperands() {
  ATO_OPERANDS=()
  assertEquals "with no operands" \
    0                             \
    "$(__ato_getopt_set_operands '--name' 'hello' '--'; echo ${#ATO_OPERANDS[@]})"

  ATO_OPERANDS=()
  assertEquals "with one operand" \
    1                             \
    "$(__ato_getopt_set_operands '--name' 'hello' '--' 'first'; echo ${#ATO_OPERANDS[@]})"

  ATO_OPERANDS=()
  assertEquals "with two operands" \
    2                             \
    "$(__ato_getopt_set_operands '--name' 'hello' '--' 'first' 'second'; echo ${#ATO_OPERANDS[@]})"
}

source $(dirname $0)/shunit/src/shunit2

# vim: ft=sh
