#!/usr/bin/env bash
source $(dirname $0)/../lib/option_manipulator.inc

function testOptionSave() {
  assertEquals "can add to array"            \
    "a b c d"                                 \
    "$(__pgop_option_save global 'a b c d' && echo ${PGOP_GLOBAL[0]})"

  assertEquals "can edit array"            \
    "a a a a"                                 \
    "$(
      __pgop_option_save global 'a b c d';
      __pgop_option_save global 'a a a a' 0;
      echo ${PGOP_GLOBAL[0]}
    )"
}

source $(dirname $0)/shunit/src/shunit2

# vim: ft=sh
